import type { AppItem, BlogPost, ChangeType, PatchNote, PatchType, RequestItem, RequestStatus, SkillGroup } from "./types";
export const APPS: AppItem[] = [
  {
    id: 1,
    name: "TaskFlow",
    tagline: "마감일 걱정 없는 할일 관리",
    description: "칸반 보드와 타임라인을 결합한 스마트 할일 관리 앱. 반복 일정, 우선순위 태그, 팀 공유 기능 지원.",
    category: "생산성",
    tech: ["React", "TypeScript", "Zustand", "Tailwind"],
    platform: ["Web", "PWA"],
    version: "2.3.1",
    stars: 142,
    downloads: 1840,
    status: "active",
    link: "#",
    isNew: false,
    isFeatured: true,
    features: [
      "칸반 보드 & 리스트 뷰 전환",
      "반복 일정 설정 (매일/매주/매월)",
      "우선순위 4단계 태그 시스템",
      "마감일 기반 타임라인 뷰",
      "팀원 초대 및 작업 공유",
      "PWA — 모바일 홈화면 설치 지원",
    ],
    techDetail: "React 18 + TypeScript 기반. 상태관리는 Zustand로, 복잡한 보일러플레이트 없이 간결하게 처리. 드래그 앤 드롭은 @dnd-kit 라이브러리 사용. PWA는 Vite PWA 플러그인으로 서비스 워커 자동 생성. 팀 공유는 Firebase Realtime Database 활용.",
    screenshots: [
      { label: "칸반 보드", accent: "#0099bb" },
      { label: "타임라인 뷰", accent: "#7c3aed" },
      { label: "상세 카드", accent: "#059669" },
    ],
  },
  {
    id: 2,
    name: "CodeSnap",
    tagline: "코드를 아름다운 이미지로",
    description: "브라우저에서 바로 코드 스니펫을 고해상도 이미지로 변환. 20가지 테마, 커스텀 폰트 지원.",
    category: "개발도구",
    tech: ["Electron", "JavaScript", "highlight.js"],
    platform: ["Windows", "macOS", "Linux"],
    version: "1.1.0",
    stars: 89,
    downloads: 620,
    status: "active",
    link: "#",
    isNew: true,
    isFeatured: false,
    features: [
      "20가지 내장 색상 테마",
      "PNG / SVG / WebP 고해상도 내보내기",
      "커스텀 폰트 로드 지원",
      "배경 색상 및 그라디언트 설정",
      "코드 창 그림자·패딩 조절",
      "100+ 언어 문법 강조",
    ],
    techDetail: "Electron 28 기반 크로스 플랫폼 데스크탑 앱. 코드 렌더링은 highlight.js + DOM-to-image-more 라이브러리로 처리. 고해상도 내보내기는 devicePixelRatio × 3 오버샘플링 후 캔버스 리사이즈. 테마 시스템은 JSON 파일 기반으로 커뮤니티 테마 추가 가능.",
    screenshots: [
      { label: "에디터 뷰", accent: "#7c3aed" },
      { label: "테마 선택", accent: "#db2777" },
      { label: "내보내기", accent: "#d97706" },
    ],
  },
  {
    id: 3,
    name: "BudgetMate",
    tagline: "월급날이 기다려지는 가계부",
    description: "카테고리 자동 분류, 월별 분석 차트, 절약 목표 설정. 은행 연동 없이 스마트한 지출 관리.",
    category: "금융",
    tech: ["Flutter", "Dart", "SQLite", "Riverpod"],
    platform: ["Android", "iOS"],
    version: "3.0.2",
    stars: 213,
    downloads: 3200,
    status: "active",
    link: "#",
    isNew: false,
    isFeatured: true,
    features: [
      "지출 카테고리 자동 분류 (AI 기반)",
      "월별 / 연간 지출 분석 차트",
      "절약 목표 설정 및 달성률 추적",
      "외화 자동 환율 변환",
      "CSV 내보내기",
      "완전 오프라인 작동 (데이터 로컬 저장)",
    ],
    techDetail: "Flutter 3.19 + Dart. 상태관리는 Riverpod 2.0. 로컬 DB는 SQLite (sqflite 패키지). 차트는 fl_chart 라이브러리. 카테고리 자동 분류는 on-device TFLite 모델 사용으로 서버 없이 작동. 오프라인 우선 설계로 인터넷 없이도 100% 기능 사용 가능.",
    screenshots: [
      { label: "대시보드", accent: "#059669" },
      { label: "지출 입력", accent: "#0099bb" },
      { label: "분석 차트", accent: "#d97706" },
    ],
  },
  {
    id: 4,
    name: "GitPulse",
    tagline: "내 GitHub 활동을 한눈에",
    description: "커밋 히스토리, 언어 분포, 기여도 히트맵을 인터랙티브 대시보드로 시각화.",
    category: "개발도구",
    tech: ["React", "GitHub API", "Recharts", "TypeScript"],
    platform: ["Web"],
    version: "1.4.0",
    stars: 176,
    downloads: 990,
    status: "active",
    link: "#",
    isNew: false,
    isFeatured: false,
    features: [
      "연간 기여도 히트맵 시각화",
      "저장소별 언어 분포 차트",
      "커밋 시간대·요일 분포 분석",
      "Organization 저장소 통계 포함",
      "공개 프로필 링크 생성",
      "GitHub Token 없이 공개 저장소 조회 가능",
    ],
    techDetail: "React + TypeScript + Recharts. GitHub REST API v3 사용. Rate limit 대응을 위해 클라이언트 측 IndexedDB 캐싱 레이어 구현 (TTL 10분). 히트맵은 SVG 직접 렌더링으로 성능 최적화. 공개 프로필 링크는 URL 쿼리 파라미터로 사용자 데이터 스냅샷 인코딩.",
    screenshots: [
      { label: "기여도 히트맵", accent: "#7c3aed" },
      { label: "언어 분포", accent: "#0099bb" },
      { label: "프로필 카드", accent: "#059669" },
    ],
  },
  {
    id: 5,
    name: "StudyTimer",
    tagline: "포모도로보다 스마트한 공부 타이머",
    description: "과목별 누적 시간, 집중도 그래프, 배경 소음으로 카페 분위기 재현. 목표 달성 알림 지원.",
    category: "교육",
    tech: ["React Native", "TypeScript", "Expo"],
    platform: ["Android", "iOS"],
    version: "2.0.5",
    stars: 98,
    downloads: 1450,
    status: "active",
    link: "#",
    isNew: true,
    isFeatured: false,
    features: [
      "과목별 누적 공부 시간 기록",
      "집중도 자가 평가 & 그래프",
      "배경 소음 8종 (카페, 빗소리, 백색소음 등)",
      "포모도로 / 자유 타이머 전환",
      "주간 목표 설정 및 달성 알림",
      "위젯 지원 (홈화면)",
    ],
    techDetail: "React Native 0.73 + Expo SDK 50. 오디오 스트리밍은 expo-av. 백그라운드 타이머는 expo-task-manager로 앱이 꺼져도 정확한 시간 추적. 위젯은 react-native-widgetkit (iOS) + react-native-android-widget.",
    screenshots: [
      { label: "타이머 화면", accent: "#db2777" },
      { label: "과목 통계", accent: "#7c3aed" },
      { label: "배경 소음 선택", accent: "#d97706" },
    ],
  },
  {
    id: 6,
    name: "WeatherNow",
    tagline: "정확한 동네 날씨 예보",
    description: "기상청 API 기반 시간별 날씨 예보, 강수 확률 그래프, 미세먼지 지수 제공. 위젯 지원.",
    category: "날씨",
    tech: ["Python", "FastAPI", "KMA API", "Vue.js"],
    platform: ["Web", "Android"],
    version: "1.2.3",
    stars: 65,
    downloads: 880,
    status: "maintenance",
    link: "#",
    isNew: false,
    isFeatured: false,
    features: [
      "기상청 단기예보 API 연동",
      "시간별 / 주간 예보",
      "강수 확률 & 강수량 그래프",
      "미세먼지·초미세먼지·자외선 지수",
      "위치 자동 감지 (GPS)",
      "홈화면 위젯 (Android)",
    ],
    techDetail: "백엔드: Python 3.11 + FastAPI. 기상청 API 데이터를 Redis로 10분 캐싱. 프론트: Vue 3 + Vite. 미세먼지는 에어코리아 API 추가 연동. 현재 점검 중인 사항: 기상청 API v2 마이그레이션.",
    screenshots: [
      { label: "메인 날씨", accent: "#2563eb" },
      { label: "주간 예보", accent: "#0099bb" },
      { label: "대기질 정보", accent: "#059669" },
    ],
  },
  {
    id: 7,
    name: "ClipBoard+",
    tagline: "클립보드 히스토리 관리자",
    description: "복사한 텍스트·이미지·파일을 최대 500개까지 저장. 태그 분류, 빠른 검색, 즐겨찾기.",
    category: "유틸",
    tech: ["Tauri", "Rust", "React", "TypeScript"],
    platform: ["Windows", "macOS"],
    version: "1.0.1",
    stars: 44,
    downloads: 310,
    status: "active",
    link: "#",
    isNew: true,
    isFeatured: false,
    features: [
      "텍스트·이미지·파일 히스토리 최대 500개",
      "태그 기반 분류 및 즐겨찾기",
      "빠른 검색 (전문 검색)",
      "글로벌 단축키로 즉시 호출",
      "항목 고정 (핀) 기능",
      "앱 종료 후에도 데이터 유지",
    ],
    techDetail: "Tauri 2.0 + Rust 백엔드 + React 프론트엔드. OS 클립보드 훅킹은 Rust arboard 크레이트. 바이너리 크기 ~5MB (Electron 대비 ~10배 경량). 이미지 저장은 Base64가 아닌 파일 경로 참조 방식으로 메모리 최적화. 검색은 Rust 측 fuzzy matching으로 50ms 이내 응답.",
    screenshots: [
      { label: "히스토리 목록", accent: "#d97706" },
      { label: "검색 팝업", accent: "#7c3aed" },
      { label: "설정 화면", accent: "#0099bb" },
    ],
  },
];

export const PATCH_NOTES: PatchNote[] = [
  {
    app: "TaskFlow", version: "2.3.1", date: "2026-06-10", type: "patch" as PatchType,
    changes: [
      { type: "fix" as ChangeType, text: "반복 일정 삭제 후에도 알림이 울리는 버그 수정" },
      { type: "fix" as ChangeType, text: "iOS Safari 드래그 앤 드롭 오동작 수정" },
      { type: "improve" as ChangeType, text: "다크모드 색상 대비 개선" },
    ],
  },
  {
    app: "BudgetMate", version: "3.0.2", date: "2026-06-05", type: "minor" as PatchType,
    changes: [
      { type: "add" as ChangeType, text: "외화 지출 자동 환율 변환 기능 추가" },
      { type: "add" as ChangeType, text: "CSV 내보내기 기능 추가" },
      { type: "fix" as ChangeType, text: "삼성페이 연동 시 중복 항목 생성 버그 수정" },
      { type: "improve" as ChangeType, text: "월별 분석 차트 렌더링 속도 40% 향상" },
    ],
  },
  {
    app: "StudyTimer", version: "2.0.5", date: "2026-05-28", type: "patch" as PatchType,
    changes: [
      { type: "add" as ChangeType, text: "빗소리, 카페 소음 등 배경음 5종 추가" },
      { type: "fix" as ChangeType, text: "Android 14 화면 꺼짐 시 타이머 일시정지 버그 수정" },
    ],
  },
  {
    app: "CodeSnap", version: "1.1.0", date: "2026-05-20", type: "minor" as PatchType,
    changes: [
      { type: "add" as ChangeType, text: "Tokyo Night, Catppuccin 테마 추가" },
      { type: "add" as ChangeType, text: "SVG, WebP 내보내기 지원" },
      { type: "improve" as ChangeType, text: "렌더링 엔진 교체로 폰트 안티앨리어싱 개선" },
    ],
  },
  {
    app: "GitPulse", version: "1.4.0", date: "2026-05-12", type: "minor" as PatchType,
    changes: [
      { type: "add" as ChangeType, text: "Organization 저장소 통계 지원" },
      { type: "add" as ChangeType, text: "공개 프로필 링크 생성 기능 추가" },
      { type: "fix" as ChangeType, text: "Private 저장소 카운트 누락 수정" },
    ],
  },
];

export const REQUESTS: RequestItem[] = [
  { id: "REQ-042", title: "TaskFlow — 구글 캘린더 연동", status: "accepted" as RequestStatus, date: "2026-05-30", eta: "2026-07-01" },
  { id: "REQ-041", title: "BudgetMate — 카카오페이 연동", status: "in-progress" as RequestStatus, date: "2026-05-18", eta: "2026-06-20" },
  { id: "REQ-040", title: "음성 메모 앱 개발 요청", status: "rejected" as RequestStatus, date: "2026-05-10", eta: null },
  { id: "REQ-039", title: "GitPulse — LinkedIn 공유 기능", status: "completed" as RequestStatus, date: "2026-04-22", eta: null },
];

export const SKILLS: SkillGroup[] = [
  { category: "Frontend", items: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Vue.js"] },
  { category: "Mobile", items: ["Flutter", "React Native", "Expo", "Dart"] },
  { category: "Backend", items: ["Python", "FastAPI", "Node.js", "PostgreSQL", "Redis"] },
  { category: "Desktop", items: ["Electron", "Tauri", "Rust"] },
  { category: "DevOps", items: ["Docker", "GitHub Actions", "Vercel", "AWS"] },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Tauri 2.0으로 ClipBoard+ 개발기: Electron과의 비교",
    category: "기술",
    tags: ["Tauri", "Rust", "Electron", "Desktop"],
    date: "2026-06-08",
    readTime: "8분",
    summary: "ClipBoard+를 개발하면서 Electron 대신 Tauri를 선택한 이유와 실제 Rust 백엔드 구현 경험을 공유합니다. 바이너리 크기 10배 차이의 비결.",
    sections: [
      { type: "h2", content: "왜 Tauri를 선택했는가" },
      { type: "p", content: "클립보드 관리 앱을 만들 때 Electron이 가장 먼저 떠올랐습니다. 하지만 Electron 앱의 기본 바이너리 크기는 50MB를 훌쩍 넘깁니다. 클립보드 유틸리티처럼 항상 백그라운드에서 실행되는 앱에게 이건 치명적입니다." },
      { type: "h2", content: "Tauri + Rust의 핵심 구조" },
      { type: "p", content: "Tauri는 프론트엔드로 시스템 WebView를 사용하고, 백엔드는 Rust로 작성합니다. 클립보드 훅킹 같은 OS 수준 작업은 Rust의 arboard 크레이트가 담당합니다." },
      { type: "code", content: "// Rust 백엔드: 클립보드 이벤트 감지\n#[tauri::command]\nfn watch_clipboard(app: AppHandle) {\n    let mut ctx = arboard::Clipboard::new().unwrap();\n    loop {\n        if let Ok(text) = ctx.get_text() {\n            app.emit(\"clipboard-change\", text).unwrap();\n        }\n        std::thread::sleep(Duration::from_millis(300));\n    }\n}" },
      { type: "h2", content: "결과: 바이너리 크기 비교" },
      { type: "ul", content: ["Electron (hello world): 145MB", "Tauri (ClipBoard+ 전체): 5.2MB", "메모리 사용량: Electron ~120MB vs Tauri ~18MB", "콜드 스타트: Electron ~2.1s vs Tauri ~0.4s"] },
      { type: "p", content: "모든 지표에서 Tauri가 압도적으로 유리했습니다. Rust 학습 비용이 있지만, 유틸리티 앱이라면 Tauri를 강력히 추천합니다." },
    ],
  },
  {
    id: 2,
    title: "GitHub API Rate Limit 극복기: GitPulse 개발 중 만난 벽",
    category: "트러블슈팅",
    tags: ["GitHub API", "Rate Limit", "IndexedDB", "캐싱"],
    date: "2026-05-30",
    readTime: "6분",
    summary: "GitPulse 개발 중 GitHub API의 시간당 60회 제한에 부딪혔습니다. IndexedDB 기반 캐싱 레이어로 이 문제를 해결한 과정을 기록합니다.",
    sections: [
      { type: "h2", content: "문제 발생: 갑자기 멈추는 대시보드" },
      { type: "p", content: "GitPulse 베타 테스트 중 '갑자기 데이터가 안 불러와진다'는 피드백이 쏟아졌습니다. 원인은 GitHub REST API의 unauthenticated 요청 제한: 시간당 60회." },
      { type: "h2", content: "해결책: TTL 기반 IndexedDB 캐시" },
      { type: "p", content: "매 렌더링마다 API를 호출하는 구조를 IndexedDB 캐싱 레이어로 교체했습니다. TTL은 10분으로 설정해 데이터 신선도와 API 사용량을 균형있게 맞췄습니다." },
      { type: "code", content: "async function fetchWithCache(url: string, ttl = 600_000) {\n  const cached = await idb.get(url);\n  if (cached && Date.now() - cached.ts < ttl) {\n    return cached.data;\n  }\n  const data = await fetch(url).then(r => r.json());\n  await idb.set(url, { data, ts: Date.now() });\n  return data;\n}" },
      { type: "ul", content: ["API 호출 횟수 94% 감소 (실측)", "평균 로딩 시간 2.1s → 80ms (캐시 히트 시)", "Rate limit 에러 발생 0건 (도입 후)"] },
    ],
  },
  {
    id: 3,
    title: "Flutter Riverpod 2.0 마이그레이션: BudgetMate의 경우",
    category: "개발일지",
    tags: ["Flutter", "Riverpod", "상태관리", "마이그레이션"],
    date: "2026-05-20",
    readTime: "10분",
    summary: "BudgetMate v2에서 v3으로 업그레이드하면서 Provider에서 Riverpod 2.0으로 상태관리를 전환한 과정. 코드량 30% 감소와 테스트 용이성 향상.",
    sections: [
      { type: "h2", content: "기존 Provider의 한계" },
      { type: "p", content: "BudgetMate v2는 Provider 패턴을 사용했습니다. 앱 규모가 커지면서 Provider의 한계가 드러났습니다: 전역 상태 의존성 관리, 위젯 트리 외부 접근 불가, 비동기 상태 처리의 복잡성." },
      { type: "h2", content: "Riverpod 2.0의 핵심 개념" },
      { type: "code", content: "// 이전 (Provider)\nclass BudgetProvider extends ChangeNotifier {\n  List<Expense> _expenses = [];\n  void addExpense(Expense e) {\n    _expenses.add(e);\n    notifyListeners();\n  }\n}\n\n// 이후 (Riverpod 2.0 - Notifier)\n@riverpod\nclass BudgetNotifier extends _$BudgetNotifier {\n  @override\n  List<Expense> build() => [];\n\n  void addExpense(Expense e) =>\n    state = [...state, e];\n}" },
      { type: "h2", content: "마이그레이션 결과" },
      { type: "ul", content: ["전체 상태관리 코드 30% 감소", "단위 테스트 작성 시간 50% 단축 (ProviderContainer 덕분)", "불필요한 rebuild 40% 감소 (select 사용)", "코드 자동완성 및 타입 추론 대폭 개선"] },
    ],
  },
  {
    id: 4,
    title: "React Native 배경음악 구현 시 오디오 세션 충돌 해결",
    category: "트러블슈팅",
    tags: ["React Native", "expo-av", "iOS", "오디오"],
    date: "2026-05-10",
    readTime: "5분",
    summary: "StudyTimer에서 배경 소음을 재생할 때 iOS에서 음악 앱 오디오가 끊기는 문제를 오디오 세션 설정으로 해결한 기록.",
    sections: [
      { type: "h2", content: "문제: 음악이 멈춘다" },
      { type: "p", content: "StudyTimer에서 카페 소음을 재생하면 스포티파이나 애플 뮤직이 즉시 정지됐습니다. iOS의 오디오 세션이 기본값으로 exclusive 모드이기 때문입니다." },
      { type: "h2", content: "해결: Audio.setAudioModeAsync" },
      { type: "code", content: "await Audio.setAudioModeAsync({\n  allowsRecordingIOS: false,\n  staysActiveInBackground: true,\n  // 핵심: 다른 앱 오디오와 믹싱\n  playsInSilentModeIOS: true,\n  shouldDuckAndroid: true,\n  interruptionModeIOS: InterruptionModeIOS.DuckOthers,\n  interruptionModeAndroid: InterruptionModeAndroid.DuckOthers,\n});" },
      { type: "p", content: "DuckOthers 모드는 다른 앱의 볼륨을 낮추면서 함께 재생합니다. 배경 소음 특성상 완전 정지보다 훨씬 자연스러운 경험을 제공합니다." },
    ],
  },
];

